//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHibernate.OData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NHibernate.OData.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare values of type &apos;{0}&apos;..
        /// </summary>
        internal static string Expression_CannotCompareTypes {
            get {
                return ResourceManager.GetString("Expression_CannotCompareTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot inverse literal of type &apos;{0}&apos;..
        /// </summary>
        internal static string Expression_CannotInverse {
            get {
                return ResourceManager.GetString("Expression_CannotInverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot negate literal of type &apos;{0}&apos;..
        /// </summary>
        internal static string Expression_CannotNegate {
            get {
                return ResourceManager.GetString("Expression_CannotNegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation &apos;{0}&apos; is not supported on type &apos;{1}&apos;..
        /// </summary>
        internal static string Expression_IncompatibleTypes {
            get {
                return ResourceManager.GetString("Expression_IncompatibleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected exponent for decimal literal at {0}..
        /// </summary>
        internal static string Lexer_DecimalCannotHaveExponent {
            get {
                return ResourceManager.GetString("Lexer_DecimalCannotHaveExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected digits after exponent at {0}..
        /// </summary>
        internal static string Lexer_ExpectedDigitsAfterExponent {
            get {
                return ResourceManager.GetString("Lexer_ExpectedDigitsAfterExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary format is invalid at {0}..
        /// </summary>
        internal static string Lexer_InvalidBinaryFormat {
            get {
                return ResourceManager.GetString("Lexer_InvalidBinaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/time format is invalid at {0}..
        /// </summary>
        internal static string Lexer_InvalidDateTimeFormat {
            get {
                return ResourceManager.GetString("Lexer_InvalidDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration format is invalid at {0}..
        /// </summary>
        internal static string Lexer_InvalidDurationFormat {
            get {
                return ResourceManager.GetString("Lexer_InvalidDurationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid format is invalid at {0}..
        /// </summary>
        internal static string Lexer_InvalidGuidFormat {
            get {
                return ResourceManager.GetString("Lexer_InvalidGuidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected exponent for long literal at {0}..
        /// </summary>
        internal static string Lexer_LongCannotHaveExponent {
            get {
                return ResourceManager.GetString("Lexer_LongCannotHaveExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpecter character &apos;{0}&apos; at offset {1}..
        /// </summary>
        internal static string Lexer_UnexpectedCharacter {
            get {
                return ResourceManager.GetString("Lexer_UnexpectedCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated string starting at {0}..
        /// </summary>
        internal static string Lexer_UnterminatedString {
            get {
                return ResourceManager.GetString("Lexer_UnterminatedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is not compatible on types &apos;{0}&apos; and &apos;{1}&apos;..
        /// </summary>
        internal static string LiteralUtil_IncompatibleTypes {
            get {
                return ResourceManager.GetString("LiteralUtil_IncompatibleTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown EDM type &apos;{0}&apos;..
        /// </summary>
        internal static string LiteralUtil_UnknownEdmType {
            get {
                return ResourceManager.GetString("LiteralUtil_UnknownEdmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast value to &apos;{0}&apos;..
        /// </summary>
        internal static string Method_CannotCast {
            get {
                return ResourceManager.GetString("Method_CannotCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {1} of method &apos;{0}&apos; must be of type &apos;{2}&apos;..
        /// </summary>
        internal static string Method_InvalidArgumentType {
            get {
                return ResourceManager.GetString("Method_InvalidArgumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot understand query string element &apos;{0}&apos;..
        /// </summary>
        internal static string ODataExpression_InvalidQueryStringElement {
            get {
                return ResourceManager.GetString("ODataExpression_InvalidQueryStringElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query string parameter &apos;{0}&apos; must be a positive integer..
        /// </summary>
        internal static string ODataExpression_SkipTopMustBePositive {
            get {
                return ResourceManager.GetString("ODataExpression_SkipTopMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {1} of method &apos;{0}&apos; must be a string literal..
        /// </summary>
        internal static string Parser_ArgumentMustBeStringLiteral {
            get {
                return ResourceManager.GetString("Parser_ArgumentMustBeStringLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse argument list..
        /// </summary>
        internal static string Parser_CannotParseArgumentList {
            get {
                return ResourceManager.GetString("Parser_CannotParseArgumentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected empty expression..
        /// </summary>
        internal static string Parser_EmptySource {
            get {
                return ResourceManager.GetString("Parser_EmptySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected binary operator..
        /// </summary>
        internal static string Parser_ExpectedBinaryOperator {
            get {
                return ResourceManager.GetString("Parser_ExpectedBinaryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected boolean expression..
        /// </summary>
        internal static string Parser_ExpectedBooleanExpression {
            get {
                return ResourceManager.GetString("Parser_ExpectedBooleanExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected boolean literal..
        /// </summary>
        internal static string Parser_ExpectedBooleanLiteral {
            get {
                return ResourceManager.GetString("Parser_ExpectedBooleanLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected identifier..
        /// </summary>
        internal static string Parser_ExpectedIdentifier {
            get {
                return ResourceManager.GetString("Parser_ExpectedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected literal..
        /// </summary>
        internal static string Parser_ExpectedLiteral {
            get {
                return ResourceManager.GetString("Parser_ExpectedLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected operator..
        /// </summary>
        internal static string Parser_ExpectedOperator {
            get {
                return ResourceManager.GetString("Parser_ExpectedOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected syntax..
        /// </summary>
        internal static string Parser_ExpectedSyntax {
            get {
                return ResourceManager.GetString("Parser_ExpectedSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0}..
        /// </summary>
        internal static string Parser_ExpectedToken {
            get {
                return ResourceManager.GetString("Parser_ExpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; expectes {1} arguments..
        /// </summary>
        internal static string Parser_IllegalArgumentCount {
            get {
                return ResourceManager.GetString("Parser_IllegalArgumentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; expects between {1} and {2} arguments..
        /// </summary>
        internal static string Parser_IllegalVarArgumentCount {
            get {
                return ResourceManager.GetString("Parser_IllegalVarArgumentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected trailing tokens..
        /// </summary>
        internal static string Parser_TrailingTokens {
            get {
                return ResourceManager.GetString("Parser_TrailingTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end..
        /// </summary>
        internal static string Parser_UnexpectedEnd {
            get {
                return ResourceManager.GetString("Parser_UnexpectedEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown method &apos;{0}&apos;..
        /// </summary>
        internal static string Parser_UnknownMethod {
            get {
                return ResourceManager.GetString("Parser_UnknownMethod", resourceCulture);
            }
        }
    }
}
